import { createContext, useContext, useState, useEffect, useCallback, useMemo } from 'react';

type Language = 'en' | 'el' | 'es' | 'fr' | 'de' | 'it';

interface Translations {
  [key: string]: {
    [key: string]: string | string[];
  };
}

const translations: Translations = {
  en: {
    // Auth page
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    haveAccount: 'Already have an account? Sign in',
    noAccount: "Don't have an account? Sign up",
    createAccount: 'Create an account to save your favorite books',
    signInToView: 'Sign in to view your saved books',
    pleaseComplete: 'Please fill in all fields',
    passwordLength: 'Password must be at least 6 characters',
    signedUpSuccess: 'Successfully signed up! You can now sign in.',
    signedInSuccess: 'Successfully signed in!',
    errorOccurred: 'An error occurred',
    loading: 'Loading...',
    or: 'or',
    // Main page
    profile: 'Profile',
    signOut: 'Sign Out',
    discoverYourNextBook: 'Discover your next book',
    describeBookAI: 'Describe the book you\'re looking for and AI will find the perfect recommendation for you.',
    searchPlaceholder: 'Describe the book you\'re looking for... e.g. I want a mystery novel from the 1930s',
    suggestMeBook: 'Suggest me a book',
    searching: 'Searching...',
    ourRecommendation: 'Our recommendation for you',
    startSearch: 'Start your search above',
    foundBook: 'Found the perfect book for you!',
    noBooks: 'No books found matching your criteria. Try a different search!',
    failedSearch: 'Failed to search for books. Please try again.',
    mustSignIn: 'You must sign in to save books.',
    bookSaved: 'Book added to your favorites!',
    failedSave: 'Failed to save book',
    signedOut: 'Successfully signed out.',
    failedSignOut: 'Failed to sign out',
    // Profile page
    myBooks: 'My Saved Books',
    noSavedBooks: 'No saved books yet',
    startSaving: 'Start searching for books and save your favorites!',
    profileSettings: 'Profile Settings',
    editProfile: 'Edit Profile',
    nickname: 'Nickname',
    saveChanges: 'Save Changes',
    savedSuccessfully: 'Saved successfully!',
    genrePreferences: 'Genre Preferences',
    selectGenres: 'Select your favorite genres',
    languagePreferences: 'Language Preferences',
    selectLanguages: 'Select your preferred reading languages',
    myLists: 'My Lists',
    createList: 'Create New List',
    listName: 'List Name',
    listDescription: 'Description',
    createNewList: 'Create List',
    friends: 'Friends',
    addFriend: 'Add Friend',
    friendsList: 'Your Friends',
    noFriends: 'No friends yet',
    profilePhoto: 'Profile Photo',
    uploadPhoto: 'Upload Photo',
    deletePhoto: 'Delete Photo',
    uploading: 'Uploading...',
    imageRequirements: 'Only images (JPEG, PNG, WebP, GIF) up to 5MB allowed',
    nicknameUnique: 'Nickname must be unique',
    fileTooLarge: 'File is too large. Maximum size: 5MB',
    invalidFileType: 'Invalid file type. Only images allowed.',
    photoUpdatedSuccess: 'Photo updated successfully!',
    photoDeletedSuccess: 'Photo deleted successfully!',
    nicknameEmpty: 'Nickname cannot be empty',
    nicknameInUse: 'This nickname is already taken. Please choose another.',
    // Random prompts
    randomPrompts: [
      'I want a mystery novel from the 1930s',
      'Looking for a sci-fi book about space exploration',
      'A romantic comedy set in Paris',
      'Historical fiction about ancient Rome',
      'A thriller with unexpected twists',
      'Fantasy novel with dragons and magic',
      'Biography of an inspiring leader',
      'Psychological horror that keeps you up at night',
      'Adventure story set in the Amazon rainforest',
      'A book about personal growth and mindfulness',
      'Classic literature from the Victorian era',
      'True story about survival against all odds',
      'Poetry collection celebrating love and life',
      'Cookbook with traditional Italian recipes',
      'Political drama set during the Cold War',
      'Coming-of-age story in a small town',
      'Epic fantasy saga with complex world-building',
      'Business book about innovation and disruption',
      'Art book about impressionist painters',
      'Sports autobiography of an Olympic champion'
    ],
  },
  el: {
    // Auth page
    signIn: 'Σύνδεση',
    signUp: 'Εγγραφή',
    email: 'Email',
    password: 'Κωδικός',
    continueWithGoogle: 'Συνέχεια με Google',
    continueWithApple: 'Συνέχεια με Apple',
    haveAccount: 'Έχετε ήδη λογαριασμό; Συνδεθείτε',
    noAccount: 'Δεν έχετε λογαριασμό; Εγγραφείτε',
    createAccount: 'Δημιουργήστε λογαριασμό για να αποθηκεύετε τα αγαπημένα σας βιβλία',
    signInToView: 'Συνδεθείτε για να δείτε τα αποθηκευμένα σας βιβλία',
    pleaseComplete: 'Παρακαλώ συμπληρώστε όλα τα πεδία',
    passwordLength: 'Ο κωδικός πρέπει να έχει τουλάχιστον 6 χαρακτήρες',
    signedUpSuccess: 'Εγγραφήκατε επιτυχώς! Μπορείτε τώρα να συνδεθείτε.',
    signedInSuccess: 'Συνδεθήκατε επιτυχώς!',
    errorOccurred: 'Παρουσιάστηκε σφάλμα',
    loading: 'Περιμένετε...',
    or: 'ή',
    // Main page
    profile: 'Προφίλ',
    signOut: 'Αποσύνδεση',
    discoverYourNextBook: 'Ανακαλύψτε το επόμενο βιβλίο σας',
    describeBookAI: 'Περιγράψτε το βιβλίο που ψάχνετε και η τεχνητή νοημοσύνη θα βρει την τέλεια σύσταση για εσάς.',
    searchPlaceholder: 'Περιγράψτε το βιβλίο που ψάχνετε... π.χ. Θέλω ένα μυστήριο μυθιστόρημα από τη δεκαετία του 1930',
    suggestMeBook: 'Πρότεινέ μου ένα βιβλίο',
    searching: 'Αναζήτηση...',
    ourRecommendation: 'Η πρότασή μας για εσάς',
    startSearch: 'Ξεκινήστε την αναζήτησή σας παραπάνω',
    foundBook: 'Βρήκαμε το τέλειο βιβλίο για εσάς!',
    noBooks: 'Δεν βρέθηκαν βιβλία που να ταιριάζουν με τα κριτήριά σας. Δοκιμάστε διαφορετική αναζήτηση!',
    failedSearch: 'Αποτυχία αναζήτησης βιβλίων. Παρακαλώ δοκιμάστε ξανά.',
    mustSignIn: 'Πρέπει να συνδεθείτε για να αποθηκεύσετε βιβλία.',
    bookSaved: 'Το βιβλίο προστέθηκε στα αγαπημένα σας!',
    failedSave: 'Αποτυχία αποθήκευσης βιβλίου',
    signedOut: 'Αποσυνδεθήκατε επιτυχώς.',
    failedSignOut: 'Αποτυχία αποσύνδεσης',
    // Profile page
    myBooks: 'Τα Αποθηκευμένα μου Βιβλία',
    noSavedBooks: 'Δεν υπάρχουν αποθηκευμένα βιβλία ακόμα',
    startSaving: 'Ξεκινήστε να αναζητάτε βιβλία και αποθηκεύστε τα αγαπημένα σας!',
    profileSettings: 'Ρυθμίσεις Προφίλ',
    editProfile: 'Επεξεργασία Προφίλ',
    nickname: 'Ψευδώνυμο',
    saveChanges: 'Αποθήκευση Αλλαγών',
    savedSuccessfully: 'Αποθηκεύτηκε επιτυχώς!',
    genrePreferences: 'Προτιμήσεις Ειδών',
    selectGenres: 'Επιλέξτε τα αγαπημένα σας είδη',
    languagePreferences: 'Προτιμήσεις Γλωσσών',
    selectLanguages: 'Επιλέξτε τις γλώσσες ανάγνωσης που προτιμάτε',
    myLists: 'Οι Λίστες μου',
    createList: 'Δημιουργία Νέας Λίστας',
    listName: 'Όνομα Λίστας',
    listDescription: 'Περιγραφή',
    createNewList: 'Δημιουργία Λίστας',
    friends: 'Φίλοι',
    addFriend: 'Προσθήκη Φίλου',
    friendsList: 'Οι Φίλοι σας',
    noFriends: 'Δεν υπάρχουν φίλοι ακόμα',
    profilePhoto: 'Φωτογραφία Προφίλ',
    uploadPhoto: 'Ανέβασμα Φωτογραφίας',
    deletePhoto: 'Διαγραφή Φωτογραφίας',
    uploading: 'Ανέβασμα...',
    imageRequirements: 'Επιτρέπονται μόνο εικόνες (JPEG, PNG, WebP, GIF) μέχρι 5MB',
    nicknameUnique: 'Το nickname πρέπει να είναι μοναδικό',
    fileTooLarge: 'Το αρχείο είναι πολύ μεγάλο. Μέγιστο μέγεθος: 5MB',
    invalidFileType: 'Μη έγκυρος τύπος αρχείου. Επιτρέπονται μόνο εικόνες.',
    photoUpdatedSuccess: 'Η φωτογραφία ενημερώθηκε επιτυχώς!',
    photoDeletedSuccess: 'Η φωτογραφία διαγράφηκε επιτυχώς!',
    nicknameEmpty: 'Το nickname δεν μπορεί να είναι κενό',
    nicknameInUse: 'Αυτό το nickname χρησιμοποιείται ήδη. Παρακαλώ επιλέξτε άλλο.',
    // Random prompts
    randomPrompts: [
      'Θέλω ένα μυστήριο μυθιστόρημα από τη δεκαετία του 1930',
      'Ψάχνω για ένα βιβλίο επιστημονικής φαντασίας για διαστημική εξερεύνηση',
      'Μια ρομαντική κωμωδία στο Παρίσι',
      'Ιστορική μυθοπλασία για την αρχαία Ρώμη',
      'Ένα θρίλερ με απροσδόκητες ανατροπές',
      'Μυθιστόρημα φαντασίας με δράκους και μαγεία',
      'Βιογραφία ενός εμπνευσμένου ηγέτη',
      'Ψυχολογικός τρόμος που σε κρατάει ξάγρυπνο',
      'Ιστορία περιπέτειας στον Αμαζόνιο',
      'Βιβλίο για προσωπική ανάπτυξη και ενσυνειδητότητα',
      'Κλασική λογοτεχνία από τη Βικτωριανή εποχή',
      'Αληθινή ιστορία επιβίωσης ενάντια σε όλες τις δυσκολίες',
      'Συλλογή ποιημάτων για την αγάπη και τη ζωή',
      'Βιβλίο μαγειρικής με παραδοσιακές ιταλικές συνταγές',
      'Πολιτικό δράμα κατά τη διάρκεια του Ψυχρού Πολέμου',
      'Ιστορία ενηλικίωσης σε μια μικρή πόλη',
      'Επική φαντασία με πολύπλοκο κόσμο',
      'Βιβλίο επιχειρήσεων για καινοτομία και διακοπή',
      'Βιβλίο τέχνης για ιμπρεσιονιστές ζωγράφους',
      'Αθλητική αυτοβιογραφία Ολυμπιονίκη'
    ],
  },
  es: {
    // Auth page
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    email: 'Correo electrónico',
    password: 'Contraseña',
    continueWithGoogle: 'Continuar con Google',
    continueWithApple: 'Continuar con Apple',
    haveAccount: '¿Ya tienes una cuenta? Inicia sesión',
    noAccount: '¿No tienes cuenta? Regístrate',
    createAccount: 'Crea una cuenta para guardar tus libros favoritos',
    signInToView: 'Inicia sesión para ver tus libros guardados',
    pleaseComplete: 'Por favor completa todos los campos',
    passwordLength: 'La contraseña debe tener al menos 6 caracteres',
    signedUpSuccess: '¡Registro exitoso! Ahora puedes iniciar sesión.',
    signedInSuccess: '¡Inicio de sesión exitoso!',
    errorOccurred: 'Ocurrió un error',
    loading: 'Cargando...',
    or: 'o',
    // Main page
    profile: 'Perfil',
    signOut: 'Cerrar sesión',
    discoverYourNextBook: 'Descubre tu próximo libro',
    describeBookAI: 'Describe el libro que buscas y la IA encontrará la recomendación perfecta para ti.',
    searchPlaceholder: 'Describe el libro que buscas... ej. Quiero una novela de misterio de los años 30',
    suggestMeBook: 'Sugiéreme un libro',
    searching: 'Buscando...',
    ourRecommendation: 'Nuestra recomendación para ti',
    startSearch: 'Comienza tu búsqueda arriba',
    foundBook: '¡Encontramos el libro perfecto para ti!',
    noBooks: 'No se encontraron libros que coincidan con tus criterios. ¡Intenta una búsqueda diferente!',
    failedSearch: 'Error al buscar libros. Por favor, inténtalo de nuevo.',
    mustSignIn: 'Debes iniciar sesión para guardar libros.',
    bookSaved: '¡Libro agregado a tus favoritos!',
    failedSave: 'Error al guardar libro',
    signedOut: 'Sesión cerrada exitosamente.',
    failedSignOut: 'Error al cerrar sesión',
    // Profile page
    myBooks: 'Mis Libros Guardados',
    noSavedBooks: 'Aún no hay libros guardados',
    startSaving: '¡Comienza a buscar libros y guarda tus favoritos!',
    profileSettings: 'Configuración del Perfil',
    editProfile: 'Editar Perfil',
    nickname: 'Apodo',
    saveChanges: 'Guardar Cambios',
    savedSuccessfully: '¡Guardado exitosamente!',
    genrePreferences: 'Preferencias de Género',
    selectGenres: 'Selecciona tus géneros favoritos',
    languagePreferences: 'Preferencias de Idioma',
    selectLanguages: 'Selecciona tus idiomas de lectura preferidos',
    myLists: 'Mis Listas',
    createList: 'Crear Nueva Lista',
    listName: 'Nombre de la Lista',
    listDescription: 'Descripción',
    createNewList: 'Crear Lista',
    profilePhoto: 'Foto de Perfil',
    uploadPhoto: 'Subir Foto',
    deletePhoto: 'Eliminar Foto',
    uploading: 'Subiendo...',
    imageRequirements: 'Solo se permiten imágenes (JPEG, PNG, WebP, GIF) hasta 5MB',
    nicknameUnique: 'El apodo debe ser único',
    fileTooLarge: 'El archivo es demasiado grande. Tamaño máximo: 5MB',
    invalidFileType: 'Tipo de archivo no válido. Solo se permiten imágenes.',
    photoUpdatedSuccess: '¡Foto actualizada exitosamente!',
    photoDeletedSuccess: '¡Foto eliminada exitosamente!',
    nicknameEmpty: 'El apodo no puede estar vacío',
    nicknameInUse: 'Este apodo ya está en uso. Por favor elige otro.',
    // Random prompts
    randomPrompts: [
      'Quiero una novela de misterio de los años 30',
      'Busco un libro de ciencia ficción sobre exploración espacial',
      'Una comedia romántica ambientada en París',
      'Ficción histórica sobre la antigua Roma',
      'Un thriller con giros inesperados',
      'Novela de fantasía con dragones y magia',
      'Biografía de un líder inspirador',
      'Terror psicológico que te mantiene despierto',
      'Historia de aventuras en la selva amazónica',
      'Libro sobre crecimiento personal y mindfulness',
      'Literatura clásica de la era victoriana',
      'Historia real sobre supervivencia contra todo pronóstico',
      'Colección de poesía celebrando amor y vida',
      'Libro de cocina con recetas italianas tradicionales',
      'Drama político durante la Guerra Fría',
      'Historia de mayoría de edad en un pueblo pequeño',
      'Saga de fantasía épica con construcción de mundo compleja',
      'Libro de negocios sobre innovación y disrupción',
      'Libro de arte sobre pintores impresionistas',
      'Autobiografía deportiva de un campeón olímpico'
    ],
  },
  fr: {
    // Auth page
    signIn: 'Se connecter',
    signUp: "S'inscrire",
    email: 'Email',
    password: 'Mot de passe',
    continueWithGoogle: 'Continuer avec Google',
    continueWithApple: 'Continuer avec Apple',
    haveAccount: 'Vous avez déjà un compte? Connectez-vous',
    noAccount: "Vous n'avez pas de compte? Inscrivez-vous",
    createAccount: 'Créez un compte pour sauvegarder vos livres préférés',
    signInToView: 'Connectez-vous pour voir vos livres sauvegardés',
    pleaseComplete: 'Veuillez remplir tous les champs',
    passwordLength: 'Le mot de passe doit contenir au moins 6 caractères',
    signedUpSuccess: 'Inscription réussie! Vous pouvez maintenant vous connecter.',
    signedInSuccess: 'Connexion réussie!',
    errorOccurred: 'Une erreur est survenue',
    loading: 'Chargement...',
    or: 'ou',
    // Main page
    profile: 'Profil',
    signOut: 'Se déconnecter',
    discoverYourNextBook: 'Découvrez votre prochain livre',
    describeBookAI: 'Décrivez le livre que vous recherchez et l\'IA trouvera la recommandation parfaite pour vous.',
    searchPlaceholder: 'Décrivez le livre que vous cherchez... ex. Je veux un roman policier des années 1930',
    suggestMeBook: 'Suggérez-moi un livre',
    searching: 'Recherche...',
    ourRecommendation: 'Notre recommandation pour vous',
    startSearch: 'Commencez votre recherche ci-dessus',
    foundBook: 'Nous avons trouvé le livre parfait pour vous!',
    noBooks: 'Aucun livre trouvé correspondant à vos critères. Essayez une recherche différente!',
    failedSearch: 'Échec de la recherche de livres. Veuillez réessayer.',
    mustSignIn: 'Vous devez vous connecter pour enregistrer des livres.',
    bookSaved: 'Livre ajouté à vos favoris!',
    failedSave: 'Échec de l\'enregistrement du livre',
    signedOut: 'Déconnexion réussie.',
    failedSignOut: 'Échec de la déconnexion',
    // Profile page
    myBooks: 'Mes Livres Enregistrés',
    noSavedBooks: 'Aucun livre enregistré pour le moment',
    startSaving: 'Commencez à rechercher des livres et enregistrez vos favoris!',
    profileSettings: 'Paramètres du Profil',
    editProfile: 'Modifier le Profil',
    nickname: 'Pseudonyme',
    saveChanges: 'Enregistrer les Modifications',
    savedSuccessfully: 'Enregistré avec succès!',
    genrePreferences: 'Préférences de Genre',
    selectGenres: 'Sélectionnez vos genres préférés',
    languagePreferences: 'Préférences de Langue',
    selectLanguages: 'Sélectionnez vos langues de lecture préférées',
    myLists: 'Mes Listes',
    createList: 'Créer une Nouvelle Liste',
    listName: 'Nom de la Liste',
    listDescription: 'Description',
    createNewList: 'Créer une Liste',
    profilePhoto: 'Photo de Profil',
    uploadPhoto: 'Télécharger une Photo',
    deletePhoto: 'Supprimer la Photo',
    uploading: 'Téléchargement...',
    imageRequirements: 'Seules les images (JPEG, PNG, WebP, GIF) jusqu\'à 5MB sont autorisées',
    nicknameUnique: 'Le pseudonyme doit être unique',
    fileTooLarge: 'Le fichier est trop volumineux. Taille maximale: 5MB',
    invalidFileType: 'Type de fichier non valide. Seules les images sont autorisées.',
    photoUpdatedSuccess: 'Photo mise à jour avec succès!',
    photoDeletedSuccess: 'Photo supprimée avec succès!',
    nicknameEmpty: 'Le pseudonyme ne peut pas être vide',
    nicknameInUse: 'Ce pseudonyme est déjà utilisé. Veuillez en choisir un autre.',
    // Random prompts
    randomPrompts: [
      'Je veux un roman policier des années 1930',
      'À la recherche d\'un livre de science-fiction sur l\'exploration spatiale',
      'Une comédie romantique se déroulant à Paris',
      'Fiction historique sur la Rome antique',
      'Un thriller avec des rebondissements inattendus',
      'Roman fantastique avec des dragons et de la magie',
      'Biographie d\'un leader inspirant',
      'Horreur psychologique qui vous tient éveillé',
      'Histoire d\'aventure dans la forêt amazonienne',
      'Livre sur la croissance personnelle et la pleine conscience',
      'Littérature classique de l\'ère victorienne',
      'Histoire vraie de survie contre toute attente',
      'Recueil de poésie célébrant l\'amour et la vie',
      'Livre de cuisine avec des recettes italiennes traditionnelles',
      'Drame politique pendant la Guerre froide',
      'Histoire de passage à l\'âge adulte dans une petite ville',
      'Saga fantasy épique avec construction de monde complexe',
      'Livre d\'affaires sur l\'innovation et la disruption',
      'Livre d\'art sur les peintres impressionnistes',
      'Autobiographie sportive d\'un champion olympique'
    ],
  },
  de: {
    // Auth page
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    continueWithGoogle: 'Mit Google fortfahren',
    continueWithApple: 'Mit Apple fortfahren',
    haveAccount: 'Haben Sie bereits ein Konto? Anmelden',
    noAccount: 'Kein Konto? Registrieren',
    createAccount: 'Erstellen Sie ein Konto, um Ihre Lieblingsbücher zu speichern',
    signInToView: 'Melden Sie sich an, um Ihre gespeicherten Bücher zu sehen',
    pleaseComplete: 'Bitte füllen Sie alle Felder aus',
    passwordLength: 'Das Passwort muss mindestens 6 Zeichen lang sein',
    signedUpSuccess: 'Erfolgreich registriert! Sie können sich jetzt anmelden.',
    signedInSuccess: 'Erfolgreich angemeldet!',
    errorOccurred: 'Ein Fehler ist aufgetreten',
    loading: 'Laden...',
    or: 'oder',
    // Main page
    profile: 'Profil',
    signOut: 'Abmelden',
    discoverYourNextBook: 'Entdecken Sie Ihr nächstes Buch',
    describeBookAI: 'Beschreiben Sie das Buch, das Sie suchen, und die KI findet die perfekte Empfehlung für Sie.',
    searchPlaceholder: 'Beschreiben Sie das Buch, das Sie suchen... z.B. Ich möchte einen Kriminalroman aus den 1930er Jahren',
    suggestMeBook: 'Schlagen Sie mir ein Buch vor',
    searching: 'Suche...',
    ourRecommendation: 'Unsere Empfehlung für Sie',
    startSearch: 'Starten Sie Ihre Suche oben',
    foundBook: 'Das perfekte Buch für Sie gefunden!',
    noBooks: 'Keine Bücher gefunden, die Ihren Kriterien entsprechen. Versuchen Sie eine andere Suche!',
    failedSearch: 'Fehler bei der Buchsuche. Bitte versuchen Sie es erneut.',
    mustSignIn: 'Sie müssen sich anmelden, um Bücher zu speichern.',
    bookSaved: 'Buch zu Ihren Favoriten hinzugefügt!',
    failedSave: 'Fehler beim Speichern des Buches',
    signedOut: 'Erfolgreich abgemeldet.',
    failedSignOut: 'Fehler beim Abmelden',
    // Profile page
    myBooks: 'Meine Gespeicherten Bücher',
    noSavedBooks: 'Noch keine gespeicherten Bücher',
    startSaving: 'Beginnen Sie mit der Suche nach Büchern und speichern Sie Ihre Favoriten!',
    profileSettings: 'Profileinstellungen',
    editProfile: 'Profil Bearbeiten',
    nickname: 'Spitzname',
    saveChanges: 'Änderungen Speichern',
    savedSuccessfully: 'Erfolgreich gespeichert!',
    genrePreferences: 'Genre-Einstellungen',
    selectGenres: 'Wählen Sie Ihre Lieblingsgenres',
    languagePreferences: 'Spracheinstellungen',
    selectLanguages: 'Wählen Sie Ihre bevorzugten Leseprachen',
    myLists: 'Meine Listen',
    createList: 'Neue Liste Erstellen',
    listName: 'Listenname',
    listDescription: 'Beschreibung',
    createNewList: 'Liste Erstellen',
    profilePhoto: 'Profilbild',
    uploadPhoto: 'Foto Hochladen',
    deletePhoto: 'Foto Löschen',
    uploading: 'Hochladen...',
    imageRequirements: 'Nur Bilder (JPEG, PNG, WebP, GIF) bis 5MB erlaubt',
    nicknameUnique: 'Der Spitzname muss eindeutig sein',
    fileTooLarge: 'Die Datei ist zu groß. Maximale Größe: 5MB',
    invalidFileType: 'Ungültiger Dateityp. Nur Bilder sind erlaubt.',
    photoUpdatedSuccess: 'Foto erfolgreich aktualisiert!',
    photoDeletedSuccess: 'Foto erfolgreich gelöscht!',
    nicknameEmpty: 'Der Spitzname darf nicht leer sein',
    nicknameInUse: 'Dieser Spitzname wird bereits verwendet. Bitte wählen Sie einen anderen.',
    // Random prompts
    randomPrompts: [
      'Ich möchte einen Kriminalroman aus den 1930er Jahren',
      'Auf der Suche nach einem Science-Fiction-Buch über Weltraumforschung',
      'Eine romantische Komödie in Paris',
      'Historische Fiktion über das antike Rom',
      'Ein Thriller mit unerwarteten Wendungen',
      'Fantasy-Roman mit Drachen und Magie',
      'Biografie eines inspirierenden Führers',
      'Psycho-Horror, der Sie wach hält',
      'Abenteuergeschichte im Amazonas-Regenwald',
      'Buch über persönliches Wachstum und Achtsamkeit',
      'Klassische Literatur aus der viktorianischen Ära',
      'Wahre Geschichte über Überleben gegen alle Widrigkeiten',
      'Gedichtsammlung über Liebe und Leben',
      'Kochbuch mit traditionellen italienischen Rezepten',
      'Politisches Drama während des Kalten Krieges',
      'Coming-of-Age-Geschichte in einer Kleinstadt',
      'Epische Fantasy-Saga mit komplexem Weltenbau',
      'Geschäftsbuch über Innovation und Disruption',
      'Kunstbuch über impressionistische Maler',
      'Sportautobiografie eines olympischen Champions'
    ],
  },
  it: {
    // Auth page
    signIn: 'Accedi',
    signUp: 'Registrati',
    email: 'Email',
    password: 'Password',
    continueWithGoogle: 'Continua con Google',
    continueWithApple: 'Continua con Apple',
    haveAccount: 'Hai già un account? Accedi',
    noAccount: 'Non hai un account? Registrati',
    createAccount: 'Crea un account per salvare i tuoi libri preferiti',
    signInToView: 'Accedi per vedere i tuoi libri salvati',
    pleaseComplete: 'Compila tutti i campi',
    passwordLength: 'La password deve contenere almeno 6 caratteri',
    signedUpSuccess: 'Registrazione avvenuta con successo! Ora puoi accedere.',
    signedInSuccess: 'Accesso avvenuto con successo!',
    errorOccurred: 'Si è verificato un errore',
    loading: 'Caricamento...',
    or: 'o',
    // Main page
    profile: 'Profilo',
    signOut: 'Esci',
    discoverYourNextBook: 'Scopri il tuo prossimo libro',
    describeBookAI: 'Descrivi il libro che stai cercando e l\'IA troverà la raccomandazione perfetta per te.',
    searchPlaceholder: 'Descrivi il libro che stai cercando... es. Voglio un romanzo giallo degli anni \'30',
    suggestMeBook: 'Suggeriscimi un libro',
    searching: 'Ricerca...',
    ourRecommendation: 'La nostra raccomandazione per te',
    startSearch: 'Inizia la tua ricerca sopra',
    foundBook: 'Trovato il libro perfetto per te!',
    noBooks: 'Nessun libro trovato corrispondente ai tuoi criteri. Prova una ricerca diversa!',
    failedSearch: 'Ricerca libri fallita. Riprova.',
    mustSignIn: 'Devi accedere per salvare i libri.',
    bookSaved: 'Libro aggiunto ai tuoi preferiti!',
    failedSave: 'Salvataggio libro fallito',
    signedOut: 'Disconnessione avvenuta con successo.',
    failedSignOut: 'Disconnessione fallita',
    // Profile page
    myBooks: 'I Miei Libri Salvati',
    noSavedBooks: 'Nessun libro salvato ancora',
    startSaving: 'Inizia a cercare libri e salva i tuoi preferiti!',
    profileSettings: 'Impostazioni Profilo',
    editProfile: 'Modifica Profilo',
    nickname: 'Soprannome',
    saveChanges: 'Salva Modifiche',
    savedSuccessfully: 'Salvato con successo!',
    genrePreferences: 'Preferenze di Genere',
    selectGenres: 'Seleziona i tuoi generi preferiti',
    languagePreferences: 'Preferenze Linguistiche',
    selectLanguages: 'Seleziona le tue lingue di lettura preferite',
    myLists: 'Le Mie Liste',
    createList: 'Crea Nuova Lista',
    listName: 'Nome Lista',
    listDescription: 'Descrizione',
    createNewList: 'Crea Lista',
    profilePhoto: 'Foto Profilo',
    uploadPhoto: 'Carica Foto',
    deletePhoto: 'Elimina Foto',
    uploading: 'Caricamento...',
    imageRequirements: 'Solo immagini (JPEG, PNG, WebP, GIF) fino a 5MB consentite',
    nicknameUnique: 'Il soprannome deve essere unico',
    fileTooLarge: 'Il file è troppo grande. Dimensione massima: 5MB',
    invalidFileType: 'Tipo di file non valido. Solo immagini consentite.',
    photoUpdatedSuccess: 'Foto aggiornata con successo!',
    photoDeletedSuccess: 'Foto eliminata con successo!',
    nicknameEmpty: 'Il soprannome non può essere vuoto',
    nicknameInUse: 'Questo soprannome è già in uso. Per favore scegline un altro.',
    // Random prompts
    randomPrompts: [
      'Voglio un romanzo giallo degli anni \'30',
      'Cerco un libro di fantascienza sull\'esplorazione spaziale',
      'Una commedia romantica ambientata a Parigi',
      'Narrativa storica sull\'antica Roma',
      'Un thriller con colpi di scena inaspettati',
      'Romanzo fantasy con draghi e magia',
      'Biografia di un leader ispiratore',
      'Horror psicologico che ti tiene sveglio',
      'Storia d\'avventura nella foresta amazzonica',
      'Libro sulla crescita personale e mindfulness',
      'Letteratura classica dell\'era vittoriana',
      'Storia vera di sopravvivenza contro ogni previsione',
      'Raccolta di poesie che celebrano amore e vita',
      'Libro di cucina con ricette italiane tradizionali',
      'Dramma politico durante la Guerra Fredda',
      'Storia di formazione in una piccola città',
      'Saga fantasy epica con costruzione del mondo complessa',
      'Libro di business su innovazione e disruption',
      'Libro d\'arte sui pittori impressionisti',
      'Autobiografia sportiva di un campione olimpico'
    ],
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string | string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = useCallback((lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  }, []);

  const t = useCallback((key: string): string | string[] => {
    return translations[language][key] || key;
  }, [language]);

  const contextValue = useMemo(() => ({ 
    language, 
    setLanguage: handleSetLanguage, 
    t 
  }), [language, handleSetLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};